### ISSUE TITLE
USB4085 Not easy to buy and expensive

### ISSUE THREAD

**Issue by TZKJ2008** [coseyfannitutti/discipad#2]
I have contacted many suppliers, they said that this specification is rarely made and sold, it is a special model, I hope you can change to a more commonly used model, thank you!

**Comment by coseyfannitutti** [comment]
Digikey currently has nearly 8000 available for about $1 and export.farnell.com in Europe also stocks them regularly.

Because it is in fact available I would rather not change it, but it is licensed to allow you to change the footprint and produce the board yourself if shipping usb4085-gf-a port is expensive to your country.
